#!/usr/bin/env python3
"""Build local embeddings index from semantic source records."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Sequence

import numpy as np
from sentence_transformers import SentenceTransformer


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build local semantic index for books.")
    parser.add_argument(
        "--semantic-source",
        type=Path,
        default=Path("./output/semantic_source.jsonl"),
        help="Path to semantic source JSONL generated by index_books.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("./output/semantic_index"),
        help="Directory where vectors and metadata artifacts are written.",
    )
    parser.add_argument(
        "--model",
        default="sentence-transformers/all-MiniLM-L6-v2",
        help="Sentence-transformers model name.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=32,
        help="Embedding batch size.",
    )
    return parser.parse_args(argv)


def load_records(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Semantic source not found: {path}")

    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def build_embedding_text(record: Dict[str, Any]) -> str:
    if "chunk_text" in record:
        parts = [
            str(record.get("title", "") or ""),
            str(record.get("category", "") or ""),
            str(record.get("learning_mode", "") or ""),
            str(record.get("source_type", "") or ""),
            str(record.get("section_label", "") or ""),
            str(record.get("chunk_order", "") or ""),
            str(record.get("chunk_len", "") or ""),
            str(record.get("chunk_text", "") or ""),
        ]
        return "\n".join(part for part in parts if part.strip())

    parts = [
        str(record.get("title", "") or ""),
        str(record.get("category", "") or ""),
        str(record.get("learning_mode", "") or ""),
        str(record.get("metadata_text", "") or ""),
        str(record.get("body_preview", "") or ""),
    ]
    keywords = record.get("matched_keywords", [])
    if isinstance(keywords, list):
        parts.append(" ".join(str(item) for item in keywords))
    return "\n".join(part for part in parts if part.strip())


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    rows = load_records(args.semantic_source)
    if not rows:
        print("No semantic source rows found.")
        return 1

    texts = [build_embedding_text(row) for row in rows]
    model = SentenceTransformer(args.model)
    vectors = model.encode(
        texts,
        batch_size=max(1, args.batch_size),
        normalize_embeddings=True,
        convert_to_numpy=True,
        show_progress_bar=True,
    )
    vectors = np.asarray(vectors, dtype=np.float32)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    np.save(args.output_dir / "vectors.npy", vectors)
    with (args.output_dir / "metadata.json").open("w", encoding="utf-8") as handle:
        json.dump(rows, handle, ensure_ascii=False, indent=2)
    with (args.output_dir / "model_info.json").open("w", encoding="utf-8") as handle:
        json.dump({"model_name": args.model, "num_items": len(rows)}, handle, indent=2)

    indexed_kind = "chunks" if rows and "chunk_text" in rows[0] else "books"
    print(f"Wrote semantic index to: {args.output_dir.resolve()}")
    print(f"Indexed {indexed_kind}: {len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

